### ISSUE TITLE
Score Update Before Noon

### ISSUE THREAD

**Issue by kari-chen** [Rochester-Biomedical-DS/Hackathon-Summer-2022#2]
Hello! 

The scoreboard was updated before noon, so our team's most recent submission at 11:46 am was not graded. I was wondering if the organizers intend to regrade submissions today.

Thank you for your time!

**Comment by amandalarracuente** [comment]
Sorry about posting scores early yesterday. The new scores are posted now.

**Comment by dskrill** [comment]
It looks like the update today was evaluated at 11:22 AM. Is it possible to post another update so that predictions submitted shortly before noon can be evaluated?

Thanks!
