### ISSUE TITLE
Issues with uploading

### ISSUE THREAD

**Issue by a-georgiadis** [Rochester-Biomedical-DS/Hackathon-Summer-2022#3]
Hi,

We have been trying to troubleshoot uploading our predictions for the past two cycles of reading. We don't know why our results aren't being read as they are in an identical format to the example document. Any help with this would be much appreciated.

Best,
Midnight Chasers

**Comment by SamWright822** [comment]
It could be that your fork is named Hackathon-Summer-2023 instead of Hackathon-Summer-2022 ? just a guess

**Comment by amandalarracuente** [comment]
It's not exactly the same- change the name of your first column to 'DIFF' like the example file.

**Comment by a-georgiadis** [comment]
Thank you for the help. We didn't think that would be an issue as it says in the evaluations that it would read the first column of data regardless of name.

**Comment by amandalarracuente** [comment]
Yes, sorry about that. We swapped scoring schemes today. New scores are now posted.
